spring:
  application:
    name: test

server:
  port: 8081

openai:
  api-key: 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
  base-url: https://openrouter.ai/api/v1
  model-name: deepseek/deepseek-chat-v3
  temperature: 0.2